---
# Backend Service
apiVersion: v1
kind: Service
metadata:
  name: todo-backend
  labels:
    {{- include "todo-chart.backendLabels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: 8000
      {{- if eq .Values.backend.service.type "NodePort" }}
      nodePort: {{ .Values.backend.service.nodePort }}
      {{- end }}
      protocol: TCP
      name: http
  selector:
    {{- include "todo-chart.backendSelectorLabels" . | nindent 4 }}
---
# Frontend Service
apiVersion: v1
kind: Service
metadata:
  name: todo-frontend
  labels:
    {{- include "todo-chart.frontendLabels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: 3000
      {{- if eq .Values.frontend.service.type "NodePort" }}
      nodePort: {{ .Values.frontend.service.nodePort }}
      {{- end }}
      protocol: TCP
      name: http
  selector:
    {{- include "todo-chart.frontendSelectorLabels" . | nindent 4 }}
